### PR TITLE
Navigation bar updated for v1.1 design

### LINKED ISSUE #164: Convert main navigation bar
Convert the main navigation bar as a React component to adapt all the breakpoints of `v1.1` design. Use CSS Grid system to design its layout. Also integrate it with existing pages of the website..

### LINKED ISSUE #190: Pointer icon does not change to finger when hovering over hamburger icon.
**Steps to reproduce:**
1. Resize browser window so that main navigation bar elements change to a hamburger menu.
2. Hover mouser pointer over hamburger icon.

**Expected result:**
Pointer icon changes to finger icon (as when hovering over a hyperlink).
**Actual result:**
Icon does not change:
image

Found testing PR #170

### LINKED ISSUE #191: Get involved" button doesn't work in Firefox
"Get involved" from main navigation bar should take user to:
https://deploy-preview-170--keen-stonebraker-bb1a10.netlify.com/get-involved/
It functions OK in Chrome but does NOT function in FF (not pointer does not turn into a finger when over the button and no URL is displayed in bottom corner of browser window):
https://deploy-preview-170--keen-stonebraker-bb1a10.netlify.com/get-involved/
image

### LINKED ISSUE #192: Background page scrolls when hamburger menu is exposed.

### LINKED ISSUE #194: Double scroll bars on screen when hamburger menu open

### PR DESCRIPTION
**Pull request by shankar2105**
Fixes #164 Updated Header for v1.1 design and removed previous header component.
Fixes #191 - Get involved" button doesn't work in Firefox
Fixes #190 - Pointer icon does not change to finger when hovering over hamburger icon.
Fixes #192 - Disable body scroll on mobile menu active
Also Fixes #194, #195, #196

### CODE REVIEW

File: src/containers/App.js [hunk 1]
```diff
@@ -4,7 +4,8 @@ import { hot } from 'react-hot-loader'
 //
 import Routes from 'react-static-routes'
 
-import Header from './partials/header';
+// import Header from './partials/header';
+import Header from '../v1.1/components/global_header/index';
```
Comment (joshuef) [inline src/containers/App.js]: @shankar2105 why are we internally versioning our components? Let's just update the relevant components, or create a new one if something new is needed

File: src/v1.1/components/global_header/index.js [hunk 2]
```diff
@@ -0,0 +1,53 @@
+import React, { Component } from 'react'
+import { withRouter } from 'react-static'
+import classNames from 'classnames'
+//
```
Comment (joshuef) [inline src/v1.1/components/global_header/index.js]: lets get rid of unneeded comments

File: src/v1.1/components/global_header/index.js [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+import { isMenuLight } from '../../utils'
+//
+import './style.sass'
+//
+class GlobalHeader extends Component {
+  state = {
+    active: false,
+  }
+
+  componentDidUpdate(prev) {
```
Comment (joshuef) [inline src/v1.1/components/global_header/index.js]: can we pass in `active` as a prop as opposed to deriving it here in the component?

That would make this easier to write tests for

File: src/v1.1/components/global_header/index.js [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+    if (prev.location.pathname !== this.props.location.pathname) {
+      this.setState({ active: false })
+    }
+  }
+
+  render() {
+    const { location } = this.props
+    const { active } = this.state
+    const headerClasses = classNames('gHeader', {
```
Comment (joshuef) [inline src/v1.1/components/global_header/index.js]: what does `gHeader` stand for? Maybe we can get a more descriptive name?

File: src/v1.1/components/global_header/style.sass [hunk 5]
```diff
@@ -0,0 +1,123 @@
...
+    overflow-y: auto
+    .mobNav
+      &__btn
+        background-image: url($menu-close-icon) !important
+        background-color: $white !important
+        background-size: 24px
+  &__wrap
+    +clearfix()
+    +grid()
+  &__lsec,
```
Comment (joshuef) [inline src/v1.1/components/global_header/style.sass]: naming here could be vastly improved.

Why not have separate classes for this? I don't think indentation / appending class names brings much to the table (and is confusing to reason about...)

File: src/v1.1/components/main_nav/index.js [hunk 6]
```diff
@@ -0,0 +1,74 @@
+import React, { Component } from 'react'
+import { Link } from 'react-static'
+import classNames from 'classnames'
+//
+import { genRandomKey } from '../../utils'
+//
+import './style.sass'
+
+export default class MainNav extends Component {
+  items = [
```
Comment (joshuef) [inline src/v1.1/components/main_nav/index.js]: Lets import these constants from some external file? (where we could update i18n or some such as needed)

File: src/v1.1/components/main_nav/index.js [hunk 7]
```diff
@@ -0,0 +1,74 @@
...
+    const isLightTheme = (location.pathname === '/get-involved/')
+
+    return (
+      <div className={classNames('mainNav', {
+        light: isLightTheme
+      })}>
+        <div className="mainNav__wrap">
+          {
+            this.items.map(i => (
+              <div
```
Comment (joshuef) [inline src/v1.1/components/main_nav/index.js]: Lets create another component for the `item` portion of the menus.

File: src/v1.1/components/site_logo/index.js [hunk 8]
```diff
@@ -0,0 +1,23 @@
+import React, { Component } from 'react'
+import classNames from 'classnames'
+//
+import siteLogo from '../../../assets/images/common/site_logo.svg'
```
Comment (joshuef) [inline src/v1.1/components/site_logo/index.js]: maybe look at `alias`ing to avoid the need for such realtive file paths `../../..` etc

File: src/v1.1/components/site_logo/index.js [hunk 9]
```diff
@@ -0,0 +1,23 @@
+import React, { Component } from 'react'
+import classNames from 'classnames'
+//
```
Comment (joshuef) [inline src/v1.1/components/site_logo/index.js]: remove the comments

File: src/v1.1/components/site_logo/index.js [hunk 10]
```diff
@@ -0,0 +1,23 @@
...
+export default class SiteLogo extends Component {
+  render() {
+    return (
+      <div className={classNames('siteLogo', {
+        light: this.props.light,
+      })}>
+        <div className="siteLogo__wrap">
+          <a href="/">
+            <div className="siteLogo__media"><img src={siteLogo} alt="Safe Network Logo" /></div>
+            <div className="siteLogo__name">Safe Network</div>
```
Comment (joshuef) [inline src/v1.1/components/site_logo/index.js]: This text we should be pulling from a constants / language file.

(or be passed into the component from such a file/the parent)

File: src/v1.1/components/global_header/style.sass [hunk 11]
```diff
@@ -0,0 +1,123 @@
...
+// XLarge
+@media screen and (min-width: $width-xl)
+  .gHeader
+    &__lsec
+      padding-left: 140px
+    &__rsec
+      grid-column: 6/ span 5
+
+// Large
+@media screen and (max-width: $width-xl - 1) and (min-width: $width-l)
```
Comment (JimCollinson) [inline src/v1.1/components/global_header/style.sass]: @shankar2105 Let's talk through how we are setting up these breakpoints; we want them to cascade, so we should be having both min and max.

File: src/v1.1/styles/fonts.sass [hunk 12]
```diff
@@ -0,0 +1,5 @@
+=font-1
+  font-family: 'Halis Round','Montserrat','Roboto', Arial, sans-serif
+
+=font-2
+  font-family: 'Campton','Montserrat', Arial, sans-serif
```
Comment (JimCollinson) [inline src/v1.1/styles/fonts.sass]: Deprecating Campton BTW

File: src/v1.1/styles/variables.sass [hunk 13]
```diff
@@ -0,0 +1,19 @@
+// Grid
+$width-xl: 2200px
+$width-l: 1800px
+$width-ml: 1600px
```
Comment (JimCollinson) [inline src/v1.1/styles/variables.sass]: There is no ML size really... it's the default when no breakpoint is specified.

The (WIP) sizes as per figma are:

XL: ≥ 2200
L: ≥ 1800

M: ≤ 1600
S: ≤ 1300
XS: ≤ 1000
XXS: < 768

Although we may move them about slightly if we add in another major breakpoint.

File: src/containers/App.js (hunk 1 above)
Comment (shankar2105) [reply src/containers/App.js]: The idea behind this is, with v1.1 we are updating the component folder structure to be `Component-centric` file layout, keeping all the code that belongs to a component within a single folder. Separating this from the older code could make the development process earier and clear. When all pages are converted to v1.1 we can remove the versioning and we can get all the code directly within `src` folder.

File: src/v1.1/components/global_header/index.js (hunk 2 above)
Comment (shankar2105) [reply src/v1.1/components/global_header/index.js]: We have those empty comments to separate different imports. The ordering that was followed here is 1. default node modules 2. dev dependencies and finally project module imports. This make the code clean instead having all imports together. Also with this we can able to follow the `eslint` rule in ordering the imports.

File: src/v1.1/styles/fonts.sass (hunk 12 above)
Comment (shankar2105) [reply src/v1.1/styles/fonts.sass]: Here we have implented the text`SAFE NETWORK` of the site-logo as html text, not as an image. Figma design still have that text in `Campton` font-face. Should we change this to image or should be still use the `Campton` font-face for that text?

File: src/containers/App.js (hunk 1 above)
Comment (joshuef) [reply src/containers/App.js]: Aha, so for now it's due to keeping SOME old code. And working alongside a new structure.

So it's not possible to just update all pages to the new component at once? Global header all the things? That would be cleaner IMO. 

(But, if that not possible, this makes sense.)

File: src/v1.1/components/global_header/index.js (hunk 2 above)
Comment (joshuef) [reply src/v1.1/components/global_header/index.js]: Yeh, I'd favour implementing eslint over comments to separate (on which... why, why not just a space?).

If we have code rules, let's add them to eslint 👍 . That could be done as a separate commit on this PR, I think.

File: src/containers/App.js (hunk 1 above)
Comment (shankar2105) [reply src/containers/App.js]: We're trying to revamp all the pages under v1.1 so we don't want to spend separately to update all pages. We will remove the old pages by revamping with the new one. And finally, once all the pages got updated we can pull down those new structure into the main src directory.

File: src/v1.1/components/global_header/index.js (hunk 2 above)
Comment (shankar2105) [reply src/v1.1/components/global_header/index.js]: Can I put the the `eslint integration` as a separate task?

Comment (joshuef) [reply src/v1.1/components/global_header/index.js]: sure

Comment (joshuef) [reply src/v1.1/components/global_header/index.js]: (can you link to the issue once it's set up please)

File: src/v1.1/components/main_nav/index.js [hunk 14]
```diff
@@ -0,0 +1,62 @@
...
+import { Link } from 'react-static'
+import classNames from 'classnames'
+//
+import Button from '../button/index'
+import { genRandomKey } from '../../utils'
+//
+import content from './content.json'
+import './style.sass'
+
+const NavItem = props => {
```
Comment (joshuef) [inline src/v1.1/components/main_nav/index.js]: This should be in its own file @shankar2105

File: src/v1.1/utils.js [hunk 15]
```diff
@@ -0,0 +1,7 @@
+export const genRandomKey = () => (
```
Comment (joshuef) [inline src/v1.1/utils.js]: are there non 1.1 utils these conflict with @shankar2105 ?

Comment (shankar2105) [reply src/v1.1/utils.js]: I brought them under a single file @joshuef

File: src/v1.1/components/global_header/index.js (hunk 2 above)
Comment (shankar2105) [reply src/v1.1/components/global_header/index.js]: Linter check issue is here #182 @joshuef
